### ISSUE TITLE
Bridge plugin does not compile on UE 5.7: two 5.8-only APIs used unguarded

### ISSUE THREAD

**Issue by db-lyon** [db-lyon/ue-mcp#865]
Compiling `plugin/ue_mcp_bridge/` against a real UE 5.7 install (`C:\Program Files\Epic Games\UE_5.7`) fails. Two separate 5.8-only APIs are used without a version gate. This is a real compile, not an inference. The `FActorDesc` break from #805 is confirmed fixed: the 5.7 compile produced no `FActorDesc` error.

### 1. `FCoreDelegates::ApplicationHeartbeat` does not exist before 5.8

`plugin/ue_mcp_bridge/Source/UE_MCP_BridgeStatus/Private/MCPEngineStatus.cpp:74` and `:130`

```
error C2039: 'ApplicationHeartbeat': is not a member of 'FCoreDelegates'
error C2065: 'ApplicationHeartbeat': undeclared identifier
```

Header evidence:

- 5.8 `Engine/Source/Runtime/Core/Public/Misc/CoreDelegates.h:454`
  `static CORE_API TTSMulticastDelegate<void()> ApplicationHeartbeat;`
- 5.7 same file: no such member. `ApplicationHeartbeat` appears nowhere in 5.7 Core.
- 5.8 `Misc/FeedbackContext.h:108` broadcasts it from `FFeedbackContext::ProgressReported`; in 5.7 (`FeedbackContext.h:103`) that method is an empty virtual: `virtual void ProgressReported( const float TotalProgressInterp, FText DisplayMessage ) {}`

### 2. `UMaterial::SetMaterialUsage` arity changed in 5.8

`plugin/ue_mcp_bridge/Source/UE_MCP_Bridge/Private/Handlers/MaterialHandlers.cpp:2503` and `:2601`

```
error C2660: 'UMaterial::SetMaterialUsage': function does not take 1 arguments
```

Header evidence (`Engine/Source/Runtime/Engine/Public/Materials/Material.h`):

- 5.7:1517 `ENGINE_API bool SetMaterialUsage(bool &bNeedsRecompile, const EMaterialUsage Usage, UMaterialInterface* MaterialInstance = nullptr);` (only form)
- 5.8:1310 `ENGINE_API virtual bool SetMaterialUsage(EMaterialUsage Usage) override;`
- 5.8:1569 keeps the old form as `UE_DEPRECATED(5.8, ...)` inline shim that forwards and drops the out param.

### Fix

Gate both behind the existing `UE_MCP_HAS_5_8_API` idiom from `UE_MCP_Bridge/Public/HandlerUtils.h`.
