### ISSUE TITLE
StateTreeHandlers.cpp fails to compile on UE 5.6 - UE_MCP_HAS_STATETREE_EXECUTION_RUNTIME_DATA gated at >=6 but API is 5.7+

### ISSUE THREAD

**Issue by xlucky13z** [db-lyon/ue-mcp#536]
**Environment:** ue-mcp 1.0.74 | UE 5.6 (launcher build) | MSVC 14.38 | Win64

  ## Symptom

  `ue-mcp build` (and any editor build) fails to compile the bridge against UE 5.6:

  ```
  StateTreeHandlers.cpp(556): error C2039: 'GetExecutionRuntimeDataType' is not a member of 'FStateTreeNodeBase'
  StateTreeHandlers.cpp(558): error C2039: 'ExecutionRuntimeData' is not a member of 'FStateTreeEditorNode'
  ```

  ## Root cause

  `Source/UE_MCP_Bridge/Private/Handlers/StateTreeHandlers.cpp:38`:

  ```cpp
  #define UE_MCP_HAS_STATETREE_EXECUTION_RUNTIME_DATA (ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 6))
  ```

  `FStateTreeNodeBase::GetExecutionRuntimeDataType()` and `FStateTreeEditorNode::ExecutionRuntimeData` do not exist until UE 5.7. In 5.6, `FStateTreeNodeBase` only exposes `GetInstanceDataType()`.
  The macro therefore evaluates `true` on 5.6 and compiles the guarded block (lines 555-560) against an API that isn't present, breaking the build.

  ## Fix

  Bump the threshold to `>= 7`, matching the sibling macro on line 39 (`UE_MCP_HAS_STATETREE_GENERAL_PROPERTY_BINDING`) which already uses the correct version:

  ```cpp
  #define UE_MCP_HAS_STATETREE_EXECUTION_RUNTIME_DATA (ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 7))
  ```

  The neighbouring `>= 6` macros on lines 35-37 are correct - those APIs do exist in 5.6 and compile fine.
