### ISSUE TITLE
Linux, UE 5.8.2: UE_MCP_Bridge fails to compile (clang -Werror,-Wrange-loop-construct at 14 loops over FJsonObject::Values)

### ISSUE THREAD

**Issue by danielealbano** [db-lyon/ue-mcp#1111]
## Summary

`UE_MCP_Bridge` does not compile on Linux against Unreal Engine 5.8.2. Fourteen range-based `for` loops over `FJsonObject::Values` declare the loop variable as `const TPair<FString, TSharedPtr<FJsonValue>>&`. In 5.8 the element type of that map is `TTuple<UE::TSharedString<char16_t>, TSharedPtr<FJsonValue>>`, so the reference binds to a temporary. clang reports this under `-Wrange-loop-construct`, which the Linux toolchain treats as an error. MSVC does not diagnose it, which is probably why the plugin builds on Windows.

The same loop is still present on `main` (for example `plugin/ue_mcp_bridge/Source/UE_MCP_Bridge/Private/BridgeParamEcho.cpp`, line 60).

## Environment

- ue-mcp 1.3.8 from npm, plugin deployed with `npx ue-mcp deploy <project>.uproject`
- Unreal Engine 5.8.2, installed (binary) build, Linux x86-64, Ubuntu 24.04
- Toolchain bundled with the engine: `v26_clang-20.1.8-rockylinux8` (clang 20.1.8)
- A blank C++ project, target `<Project>Editor Linux Development`, built with `Engine/Build/BatchFiles/Linux/Build.sh`

## Error

```
AnimationHandlers_Depth.cpp:1014:54: error: loop variable 'Entry' of type 'const TPair<FString, TSharedPtr<FJsonValue>> &' (aka 'const TTuple<FString, TSharedPtr<FJsonValue>> &') binds to a temporary constructed from type 'ItElementType &' (aka 'TTuple<UE::TSharedString<char16_t>, TSharedPtr<FJsonValue>> &') [-Werror,-Wrange-loop-construct]
 1014 |         for (const TPair<FString, TSharedPtr<FJsonValue>>& Entry : (*NotifyProperties)->Values)
note: use non-reference type 'TPair<FString, TSharedPtr<FJsonValue>>' to make construction explicit or type 'const ItElementType &' to prevent copying
```

Build result: `Result: Failed (OtherCompilationError)`, 14 errors, all of this kind.

## Affected locations (1.3.8)

All under `Source/UE_MCP_Bridge/Private/`:

| File | Line |
|---|---|
| `BridgeParamEcho.cpp` | 60 |
| `Handlers/AnimationHandlers.cpp` | 1396 |
| `Handlers/AnimationHandlers_Depth.cpp` | 1014 |
| `Handlers/AnimationHandlers_IKRetargeterAuthoring.cpp` | 537, 561 |
| `Handlers/AssetHandlers_BulkProperties.cpp` | 219 |
| `Handlers/BlueprintHandlers_Depth.cpp` | 1679 |
| `Handlers/BlueprintHandlers_UserTypes.cpp` | 1216 |
| `Handlers/FoliageHandlers_Batch.cpp` | 290 |
| `Handlers/GameplayHandlers_BTAuthoring.cpp` | 516, 548 |
| `Handlers/LevelHandlers_BatchWrite.cpp` | 344, 1165 |
| `Handlers/MaterialHandlers_Build.cpp` | 178 |

Eight other loops with the same declaration compile, presumably because they iterate a container whose element really is `TPair<FString, ...>`.

## Fix that works here

Taking the loop variable by value at those 14 places, which is what the compiler suggests and what the code was already doing through the implicit temporary:

```cpp
for (const TPair<FString, TSharedPtr<FJsonValue>> Entry : (*NotifyProperties)->Values)
```

With only that change the Editor target builds: `Result: Succeeded`, 0 errors. `const auto&` would avoid the copy where the body does not need an `FString` key.

## Also seen

One deprecation warning, not an error:

```
Handlers/AssetHandlers_UV.cpp:684:46: warning: 'GetEdgeConnectedTriangles' is deprecated: Please use GetEdgeConnectedTriangleIDs() instead.
```
